ARFLAGS = crs

#For MacPorts
INCFLAGS+= -I/opt/local/include

INCFLAGS+= -I /usr/local/include/clens

#For MacPorts
LDFLAGS.EXTRA += -L/opt/local/lib

LDFLAGS.SO = -dynamiclib

LIB.SONAME = lib$(LIB.NAME).$(SO_MAJOR).dylib
LIB.DEVLNK = lib$(LIB.NAME).dylib
LIB.SHARED = lib$(LIB.NAME).$(SO_MAJOR).$(SO_MINOR).dylib
LIB.STATIC = lib$(LIB.NAME).a

PICFLAG = -fPIC

SHARED_OBJ_EXT=os
